### ISSUE TITLE
iOS compiling error

### ISSUE THREAD

**Issue by adaskaliuk** [jerson/flutter-openpgp#8]
Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_OpenpgpOptions", referenced from:
          objc-class-ref in OpenpgpPlugin.o
      "_OBJC_CLASS_$_OpenpgpKeyOptions", referenced from:
          objc-class-ref in OpenpgpPlugin.o
      "_OpenpgpNewFastOpenPGP", referenced from:
          -[OpenpgpPlugin setup] in OpenpgpPlugin.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the precompiled application for the device.

**Comment by adaskaliuk** [comment]
some more inputs

Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:105:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:123:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:141:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:159:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:177:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:195:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:213:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:232:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:251:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:270:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:289:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:308:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:327:107: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                    [self result:result output:[FlutterError errorWithCode:[NSString
                    stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                        ~~~
                                                                                                        ^~~~~~~~~~
                                                                                                        %ld
                                                                                                        (long)
    /Users/drongous/development/flutter/.pub-cache/hosted/pub.dartlang.org/openpgp-0.9.9/ios/Classes/Open
    pgpPlugin.m:347:111: warning: values of type 'NSInteger' should not be used as format arguments; add
    an explicit cast to 'long' instead [-Wformat]
                        [self result:result output:[FlutterError errorWithCode:[NSString
                        stringWithFormat:@"%ld", error.code] message:error.description details:nil]];
                                                                                                            ~~~
                                                                                                            ^~~~~~~~~~
                                                                                                            %ld
                                                                                                            (long)
    14 warnings generated.
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_OpenpgpOptions", referenced from:
          objc-class-ref in OpenpgpPlugin.o
      "_OBJC_CLASS_$_OpenpgpKeyOptions", referenced from:
          objc-class-ref in OpenpgpPlugin.o
      "_OpenpgpNewFastOpenPGP", referenced from:
          -[OpenpgpPlugin setup] in OpenpgpPlugin.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

**Comment by jerson** [comment]
hi @adaskaliuk, thanks to report the issue, im gonna check on my local environment

**Comment by jerson** [comment]
hi @adaskaliuk i been testing with a sample project using stable channel and looks like it works using 0.9.9 may you need to update some dependencies or run pod install inside ios dir, if you have an example project i can build here and check the main issue
